# mkdocs serve

site_name: Backup and Restore

site_url: https://ibm-mas-manage.github.io/backup-restore/

repo_name: GitHub
repo_url: https://github.com/ibm-mas-manage/backup-restore
edit_uri: blob/master/docs/

nav:
  #- 'Home': index.md
  #- 'Changes': changes.md
  - 'Backup and Restore': index.md
  #  - 'OCP': playbooks/ocp.md
  #  - 'Install Core': playbooks/oneclick-core.md
  #  - 'Add IoT': playbooks/oneclick-iot.md
  #  - 'Add Manage': playbooks/oneclick-manage.md
  #  - 'Add Monitor': playbooks/oneclick-monitor.md
  

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
  prev_next_buttons_location: none
extra_css:
  - extra.css
markdown_extensions:
  - toc:
      permalink: 
  - admonition
  # Add this to support expandable sections
  #- pymdownx.details

